### ISSUE TITLE
`mpi` backend failed on Census benchmark

### ISSUE THREAD

**Issue by prutskov** [modin-project/unidist#72]
```bash
Traceback (most recent call last):
  File "/localdisk/aprutsko/unidist/unidist/core/backends/mpi/core/worker.py", line 749, in <module>
    event_loop()
  File "/localdisk/aprutsko/unidist/unidist/core/backends/mpi/core/worker.py", line 675, in event_loop
    request = communication.recv_complex_operation(comm, source_rank)
  File "/localdisk/aprutsko/unidist/unidist/core/backends/mpi/core/communication.py", line 384, in recv_complex_operation
    return recv_complex_data(comm, source_rank)
  File "/localdisk/aprutsko/unidist/unidist/core/backends/mpi/core/communication.py", line 291, in recv_complex_data
    raw_buffers = [None] * raw_buffers_size
TypeError: can't multiply sequence by non-int of type 'list'
```

**Comment by YarShev** [comment]
cc @no-ponomarev

**Comment by no-ponomarev** [comment]
Not reproduced with the #74 fixes
